uni/3ºano/2ºsemestre/Opção/TPW-main/WHISP_TPW-PROJECT1/Whisp/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf.urls.static import static
from django.conf import settings
from feed import urls as feed_urls
from profiles import urls as profiles_urls
from notify import urls as notify_urls
from profiles.views import profile
from notify import views
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include(feed_urls,namespace='feed')),
    path("profile/",include(profiles_urls,namespace='profiles')),
    path("profile/", profile, name="profile"),
    path('resetpassword/', views.reset_password,name='reset_password'),
    path("",include("allauth.urls")),
    path('notify/', include(notify_urls,namespace='notify')),   
    path('chat/',include('chat.urls')) 
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

uni/3ºano/2ºsemestre/Opção/TPW-main/WHISP_TPW-PROJECT1/chat/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('',views.messages_page,name="chat"),
]

uni/3ºano/2ºsemestre/Opção/TPW-main/WHISP_TPW-PROJECT1/notify/urls.py
from django.urls import path
from . import views


app_name="notify"

urlpatterns = [
    #path('home/', views.home, name="home"),
    path("", views.listar_notificacoes, name="listar_notificacoes"),
    path('marcar_notificao_como_lida/', views.marcar_notificao_como_lida, name='marcar_notificao_como_lida'),
]   

uni/3ºano/2ºsemestre/Opção/TPW-main/WHISP_TPW-PROJECT1/notify/models.py
from django.db import models

# Create your models here.

uni/3ºano/2ºsemestre/Opção/TPW-main/WHISP_TPW-PROJECT1/notify/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .notifications import get_unread_notifications_user, count_notififications_unread_user, get_read_notifications_user
from notifications.models import Notification
#from notifications.signals import notify

#def home(request):
    #notify.send(request.user, recipient=request.user, verb=f"Olá {request.user.email}, você acessou a pagina home.", description="Descricao de qualquer coisa")
    #return HttpResponse('Você está na home')


def listar_notificacoes(request):
    unread_notifications = get_unread_notifications_user(request.user)
    read_notifications = get_read_notifications_user(request.user)
    count = count_notififications_unread_user(request.user)
    return render(request, 'listar_notificacoes.html', {'unread_notifications': unread_notifications, 'count': count, 'read_notifications': read_notifications })


def marcar_notificao_como_lida(request):
    Notification.objects.mark_all_as_read(recipient=request.user)
    return redirect('notify:listar_notificacoes')   

uni/3ºano/2ºsemestre/Opção/TPW-main/WHISP_TPW-PROJECT1/notify/templates/listar_notificacoes.html
{% extends "base.html" %}

{% block head_title %}
    {{post.text}} by {{post.author.username}}
{% endblock head_title %}

{% block body %}
<div>
    <div class="flex justify-center">
        <h3 class="text-lg font-bold font-sans text-center" style="font-size: 20px;">Novas Notificações: {{ count }}</h3>
        <button class="bg-white text-gray-800 font-bold rounded border-b-2 border-green-500 hover:border-green-600 hover:bg-green-500 hover:text-white shadow-md py-2 px-6 inline-flex items-center" style='margin-left: 15%;'>
            <a class="mr-2 text-sm" href="{% url 'notify:marcar_notificao_como_lida' %}">Marcar todas como lidas</a>
        </button>
    </div>

    <h3 style='margin-bottom: 2rem;'></h3>

    {% for notification in unread_notifications %}
    <div class="flex justify-center">
        <div class="max-w-2xl max-h-xl px-10 my-4 py-6 bg-white rounded-lg shadow-md" style='width:50rem;'>
            <div class="flex justify-between items-center w-full">
                <span class="font-light text-gray-600">{{ notification.timestamp }}</span>
            </div>
            <div class="mt-2">
                <p class="mt-3 text-gray-800 font-semibold text-lg">{{ notification.verb }}</p>
            </div>
        </div>
    </div>
    <hr>
    {% endfor %}

    {% for notification in read_notifications %}
    <div class="flex justify-center">
        <div class="max-w-2xl max-h-xl px-10 my-4 py-6 bg-white rounded-lg shadow-md" style='width:50rem;'>
            <div class="flex justify-between items-center w-full">
                <span class="font-light text-gray-600">{{ notification.timestamp }}</span>
            </div>
            <div class="mt-2">
                <p class="mt-3 text-gray-800 text-lg">{{ notification.verb }}</p>
            </div>
        </div>
        <hr>
    </div>
    <hr>
    {% endfor %}
</div>
{% endblock body %}
```


<form method="post" class="text-left px-10">
    <input type="hidden" name="csrfmiddlewaretoken" value="UsZnK37IfvyNen5OYcSFn4MiSaAEgfHpXoyZkxpmrYr69lb7k9i0FfsuZhsuvc61">
    <span name="biography" rows="4" cols="50">
    </span>
</form>