uni/3ºano/2ºsemestre/Opção/TPW-main/WHISP_TPW-PROJECT1/Whisp/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf.urls.static import static
from django.conf import settings
from feed import urls as feed_urls
from profiles import urls as profiles_urls
from notify import urls as notify_urls
from profiles.views import profile
from notify import views
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include(feed_urls,namespace='feed')),
    path("profile/",include(profiles_urls,namespace='profiles')),
    path("profile/", profile, name="profile"),
    path('resetpassword/', views.reset_password,name='reset_password'),
    path("",include("allauth.urls")),
    path('notify/', include(notify_urls,namespace='notify')),   
    path('chat/',include('chat.urls')) 
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

uni/3ºano/2ºsemestre/Opção/TPW-main/WHISP_TPW-PROJECT1/chat/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('',views.messages_page,name="chat"),
]

uni/3ºano/2ºsemestre/Opção/TPW-main/WHISP_TPW-PROJECT1/profiles/urls.py
from django.urls import path

from . import views

app_name = "profiles"

urlpatterns=[
    path("<str:username>/",views.ProfileDetailView.as_view(),name="detail"),
    path("<str:username>/follow/", views.FollowView.as_view(), name="follow"),
    
]

uni/3ºano/2ºsemestre/Opção/TPW-main/WHISP_TPW-PROJECT1/profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from sorl.thumbnail import ImageField

class Profile(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name='profile'
    )
    image = ImageField(default='profiles/default_user.jpg',upload_to='profiles')
    bg_image = ImageField(default='bg_image/back_default.jpg',upload_to='bg_image')
    biography = models.TextField(default="", max_length=500, blank=True)

    def __str__(self):
        return self.user.username

@receiver(post_save, sender=User)
def create_user_profile(sender, instance,created,**kwargs):
    if created:
        Profile.objects.create(user=instance)

uni/3ºano/2ºsemestre/Opção/TPW-main/WHISP_TPW-PROJECT1/profiles/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile



class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()
    
    class Meta:
        model = User
        fields = ['username',
                  'first_name', 'last_name', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image', 'bg_image', 'biography']
        labels = {
            'image': 'Avatar',
            'bg_image': 'Background img',
        }

uni/3ºano/2ºsemestre/Opção/TPW-main/WHISP_TPW-PROJECT1/profiles/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.http.response import HttpResponseBadRequest
from django.shortcuts import redirect, render
from django.contrib import messages
from django.views.generic import DetailView,View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView
from followers.models import Follower
from .forms import UserUpdateForm,ProfileUpdateForm
from notifications.signals import notify
from django.db.models import Q

from feed.models import Post

class ProfileDetailView(DetailView):
    http_method_names = ['get']
    template_name = "profiles/detail.html"
    model = User
    context_object_name = "user"
    slug_field = "username"
    slug_url_kwarg = "username"
    
    def dispatch(self, request, *args, **kwargs):
        self.request = request
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        user = self.get_object()

        media_filter = self.request.GET.get('filter')

        user_posts = self.get_posts_profile(user, media_filter)

        context = super().get_context_data(**kwargs)
        context['total_posts'] = Post.objects.filter(author=user).count()
        context['total_follower'] = Follower.objects.filter(following=user).count()
        context['user_posts'] = user_posts
        if self.request.user.is_authenticated:
            context['you_follow'] = Follower.objects.filter(following=user, followed_by=self.request.user).exists()
        
        context['active_filter'] =  media_filter  if  media_filter  in ['media', 'all'] else 'all'
        
        return context

    def get_posts_profile(self, user, media_filter=all):
        posts = Post.objects.filter(author=user).order_by('-date')

        if media_filter == 'media':
            posts = posts.exclude(image='', video='').exclude(image__isnull=True, video__isnull=True)
        elif media_filter == 'all':
            posts = posts.order_by('-date')
        return posts
        
        

class FollowView(LoginRequiredMixin,View):
    http_method_names = ['post']

    def post(self,request,*args,**kwargs):
        data = request.POST.dict()

        if "action" not in data or "username" not in data:
            return HttpResponseBadRequest("MISSING DATA!!")

        try:
            other_user = User.objects.get(username=data['username'])

        except User.DoesNotExist:
            return HttpResponseBadRequest("MISSING User!!")

        if data['action'] == 'follow':
            follower,created = Follower.objects.get_or_create(
                followed_by = request.user,
                following= other_user,
            )

            profile_owner = other_user
            notify.send(request.user, recipient=profile_owner, verb=f"{request.user.username} started following you.")

        else:
            try:
                follower = Follower.objects.get(
                    followed_by = request.user,
                    following= other_user,
                )
            
            except Follower.DoesNotExist:
                follower = None
            
            if follower:
                follower.delete()
        return JsonResponse({
            'success':True,
            'wording':'Unfollow' if data['action']=='follow' else 'Follow'
        })

@login_required
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST,instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES ,instance=request.user.profile)

        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request,f'Your Profile is Updated !!')
            return redirect('profile')            

    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)
    context = {
        'u_form':u_form,
        'p_form': p_form
    }
    return render(request,'profiles/edit_profile.html', context)

uni/3ºano/2ºsemestre/Opção/TPW-main/WHISP_TPW-PROJECT1/profiles/templates/profiles/detail.html
{% extends "base.html" %}
{% load thumbnail %}

{% block head_title %}
    {{ user.username }}
{% endblock head_title %}

{% block body %}
    <div class="rounded-3xl overflow-hidden shadow-xl max-w-md mx-auto my-3 text-black bg-white-500">
         {% thumbnail user.profile.bg_image "600x220" crop="center" as im %}
                <img src="{{ im.url }}" class=' -mt-3' alt='avatar'>
        {% endthumbnail %}
        <div class="flex justify-center -mt-8">
            {% thumbnail user.profile.image "110x110" crop="center" as im %}
                    <img src="{{ im.url }}" class='rounded-full border-solid border-white border-2 -mt-3' alt='avatar'>
            {% endthumbnail %}		
        </div>
        <div class="text-center px-3 pb-6 pt-2">
            <h3 class="text-lg font-bold font-sans">{{user.username}}</h3>
            <p class="text-md  font-sans">{{user.first_name}} {{user.last_name}}</p>
            {% if request.user.is_authenticated %}
                {% if request.user != user  %}
                    <div class="ml-auto">
                        <button class="bg-white text-gray-800 font-bold rounded border-b-2 border-green-500 mt-4 hover:border-green-600 hover:bg-green-500 hover:text-white shadow-md py-1 px-3 inline-flex items-center js-follow" data-username = "{{ user.username }}" type='button' data-action="{% if you_follow %}un{% endif %}follow" data-url="{% url 'profiles:follow' user.username %}">
                            <span class="mr-2 text-sm js-follow-text">
                                {% if you_follow %}
                                    UnFollow
                                {% else %}
                                    Follow
                                {% endif %}
                            </span>
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                                <path fill="currentcolor" d="M2.01 21L23 12 2.01 3 2 10l15 2-15 2z"></path>
                            </svg>
                        </button>
                    </div>
                {% endif %}
            {% else %}
                <p class='mt-3'>Login To Follow User</p>
            {% endif %}
        </div>
        <div class="flex justify-center pb-3">
            <div class="text-center mr-3 border-r pr-3">
                <h2>{{ total_posts }}</h2>
                <span>Posts</span>
            </div>
            <div class="text-center">
                <h2>{{ total_follower }}</h2>
                <span>Followers</span>
            </div>
        </div>
    </div>

    <!--Add a section for the bio -->
    <div class="rounded-3xl overflow-hidden shadow-xl max-w-md mx-auto my-3 text-black bg-white-500">
        <h3 class="text-lg font-bold font-sans text-center">Biography</h3>

        <form method="post" class="text-left px-10">
            {% csrf_token %}
            <span name="biography" rows="4" cols="50">
                {% if user.profile.biography == "" %}
                    <p class='text-gray-500'>No biography</p>
                {% else %}
                    {{ user.profile.biography }}
                {% endif %}
            </span>
        </form>
    </div>

    <div id = "posts-container" style="text-align:center;margin-top:5rem">
        <a href="?filter=media" class="{% if active_filter == 'media' %}underline{% endif %}" style="font-size:1.5rem;font-weight:500;text-decoration-color:indigo;text-decoration-thickness:0.4rem;text-decoration-skip: space;">Media</a>
        <a href="?filter=all" class="{% if active_filter == 'all' %}underline{% endif %}" style="margin-left:1.5rem;font-size:1.5rem;font-weight:500;text-decoration-color:indigo;text-decoration-thickness:0.4rem;text-decoration-skip: space;">All</a>
        {% if user_posts %}
            {% for post in user_posts %}
                {% include "includes/post.html" with post=post  show_detail_link=True %}
                <hr/>
            {% endfor %}
        {% else %}
            {% if request.user == user  %}
            <div class='text-center'>
                <p class='font-semibold text-red-500 text-4xl'>You Do not have any Posts !!</p>
            </div>  
            {% else %}
            <div class='text-center'>
                <p class='font-semibold text-red-500 text-4xl'>{{ user.username }} Do not have any Posts !!</p>
            </div>
            {% endif %}
        {% endif %}
    </div> 
    {% endblock body %}

uni/3ºano/2ºsemestre/Opção/TPW-main/WHISP_TPW-PROJECT1/profiles/templates/profiles/edit_profile.html
{% extends "base.html" %}
{% load thumbnail %}
{% block head_title %}
    Edit Profile
{% endblock %}
{% block style %}{% endblock %}

{% block body %}
    <div class="text-center">
        <div class="rounded-3xl overflow-hidden shadow-xl pb-5 w-9/12 my-5 text-black bg-gray-200 mx-auto">
            {% thumbnail user.profile.bg_image "1000x300" crop="center" as im %}
                   <img src="{{ im.url }}" class=' -mt-3' alt='avatar'>
           {% endthumbnail %}
           <div class="flex justify-center -mt-20">
               {% thumbnail user.profile.image "150x150" crop="center" as im %}
                       <img src="{{ im.url }}" class='rounded-full border-solid border-white border-2 -mt-3' alt='avatar'>
               {% endthumbnail %}		
           </div>
           <form method="post" class="text-left px-10" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset>
                <legend class="text-4xl text-extrabold text-blue-800 py-4 text-center">Profile Info</legend>
                {{ u_form }}
                {{ p_form }}
            </fieldset>
            <div class="form-group text-center my-10">
                <button type="submit" class="p-2 pl-5 pr-5 transition-colors duration-700 transform bg-indigo-500 hover:bg-blue-400 text-gray-100 text-lg rounded-lg focus:border-4 border-indigo-300">Update</button>
            </div>
        </form>
       </div>
    </div>
{% endblock body %}