uni/3ºano/2ºsemestre/Opção/TPW-main/WHISP_TPW-PROJECT1/Whisp/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf.urls.static import static
from django.conf import settings
from feed import urls as feed_urls
from profiles import urls as profiles_urls
from notify import urls as notify_urls
from profiles.views import profile
from notify import views
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include(feed_urls,namespace='feed')),
    path("profile/",include(profiles_urls,namespace='profiles')),
    path("profile/", profile, name="profile"),
    path('resetpassword/', views.reset_password,name='reset_password'),
    path("",include("allauth.urls")),
    path('notify/', include(notify_urls,namespace='notify')),   
    path('chat/',include('chat.urls')) 
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

uni/3ºano/2ºsemestre/Opção/TPW-main/WHISP_TPW-PROJECT1/chat/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('',views.messages_page,name="chat"),
]

uni/3ºano/2ºsemestre/Opção/TPW-main/WHISP_TPW-PROJECT1/feed/urls.py
from django.urls import path


from . import views


app_name = 'feed'

urlpatterns = [
    path('', views.HomePage.as_view(), name='homepage'),
    path("<int:pk>",views.DetailPostView.as_view(),name='detail'),
    path("new/",views.CreateNewPost.as_view(), name='new_post'),
    path('<int:pk>/delete/', views.DeletePost.as_view(), name='delete' ),
    path('<int:pk>/delete/comment/', views.DeleteComment.as_view(), name='deleteComment' ),
    path('follow_post/', views.FollowingHomePage.as_view(), name='follow_post' ),
    path('my_post/', views.MyPostHomePage.as_view(), name='my_post' ),
    path('like/',views.like_post,name="likepost")
]

uni/3ºano/2ºsemestre/Opção/TPW-main/WHISP_TPW-PROJECT1/notify/urls.py
from django.urls import path
from . import views


app_name="notify"

urlpatterns = [
    #path('home/', views.home, name="home"),
    path("", views.listar_notificacoes, name="listar_notificacoes"),
    path('marcar_notificao_como_lida/', views.marcar_notificao_como_lida, name='marcar_notificao_como_lida'),
]   

uni/3ºano/2ºsemestre/Opção/TPW-main/WHISP_TPW-PROJECT1/Whisp/forms.py
from django import forms
from django.contrib.auth.forms import PasswordResetForm
from django.contrib import messages

class ResetPasswordForm(forms.Form):
    email = forms.EmailField(
        label="E-mail",
        max_length=254,
        widget=forms.EmailInput(attrs={'autocomplete': 'email', 'class': 'border border-gray-300','placeholder': 'E-mail'})
    )
    new_password = forms.CharField(
        label="New Password",
        widget=forms.PasswordInput(attrs={'class': 'border border-gray-300','placeholder': 'New Password'})
    )
    confirm_new_password = forms.CharField(
        label="Confirm New Password",
        widget=forms.PasswordInput(attrs={'class': 'border border-gray-300','placeholder': 'Confirm New Password'})
    )

    def clean(self):
        cleaned_data = super().clean()
        new_password = cleaned_data.get('new_password')
        confirm_new_password = cleaned_data.get('confirm_new_password')

        if new_password != confirm_new_password:
            raise forms.ValidationError("As senhas não coincidem. Por favor, tente novamente.")

uni/3ºano/2ºsemestre/Opção/TPW-main/WHISP_TPW-PROJECT1/Whisp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import update_session_auth_hash
from .forms import ResetPasswordForm
from django.contrib import messages

def reset_password(request):
    if request.method == 'POST':
        form = ResetPasswordForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            new_password = form.cleaned_data['new_password']
            try:
                user = User.objects.get(email=email)
                user.set_password(new_password)
                user.save()
                update_session_auth_hash(request, user)
                messages.success(request, "Password Changed")
                return redirect('/')
            except User.DoesNotExist:
                pass
        else:
            messages.error(request, "Password Change Failed. Please check your inputs.")
    else:
        form = ResetPasswordForm()

    return render(request, 'account/reset_password.html', {'form': form})

uni/3ºano/2ºsemestre/Opção/TPW-main/WHISP_TPW-PROJECT1/Whisp/templates/includes/comments.html
{% load static %}

{% load thumbnail %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Whisp{% endblock %}</title>
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link rel="stylesheet" href="https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css" />
</head>

<body>
    <div class="flex justify-center">
    <div class="max-w-2xl max-h-xl px-10 my-4 py-6 bg-white rounded-lg shadow-md" style='width:50rem;'>
        <div class="flex justify-between items-center w-full">
            <span class="font-light text-gray-600">{{ comment.date|date:"F j, Y, g:i:a" }}</span>
        </div>
        <div class="mt-2">
            <p class="mt-3 text-gray-800 font-semibold text-lg">{{ comment.body }}</p>
            {% if comment.image %}
                {% thumbnail comment.image "300x300" crop="center" as im %}
                    <img src="{{ im.url }}" alt="Comment Image" class="mt-3 max-w-full">
                {% endthumbnail %}
            {% endif %}
            
            {% if comment.video %}
                <video controls class="mt-3 max-w-full auto-play-video">
                    <source src="{{ post.video.url }}" type="video/mp4">
                    Seu navegador não suporta a reprodução de vídeos.
                </video>
            {% endif %}
        </div>
        <div class="flex justify-between items-center mt-3">   
                {% if user.username == comment.author.username or user.is_superuser %}
                    <div class="m-3 mx-0 mb-0">
                        <a href="{% url 'feed:deleteComment' comment.id %}" class="bg-white text-gray-800 font-bold rounded border-b-2 border-red-500 hover:border-red-600 hover:bg-red-500 hover:text-white shadow-md py-2 px-6 inline-flex items-center delete-toggle-modal">
                            <span class="mr-2">Delete Comment</span>
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                                <path fill="currentcolor" d="M19 6.41L17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12 19 6.41z"/>
                            </svg>
                        </a>
                    </div>
            {% endif %}
            
            <div>
                <a class="flex items-center" href="{% url 'profiles:detail' post.author.username %}">
                    {% thumbnail comment.author.profile.image "373x373" crop="center" as im %}
                        <img src="{{ im.url }}" class='mx-4 w-10 h-10 object-cover rounded-full hidden sm:block' alt='avatar'>
                    {% endthumbnail %}
                    <h1 class="text-gray-700 font-bold">{{comment.author.username}}</h1>
                </a>
            </div>
        </div>
    </div>
    </div>
    <script src="{% static 'js/main.js' %}"></script>
</body>

uni/3ºano/2ºsemestre/Opção/TPW-main/WHISP_TPW-PROJECT1/Whisp/templates/includes/navbar.html
<div class="fixed h-screen flex-col w-56 bg-white rounded-r-3xl overflow-hidden">
    <div class="flex items-center justify-center h-20 shadow-md">
        <a href='/'>
            <h1 class="text-3xl uppercase  text-indigo-500">Whisp</h1>
        </a>
    </div>
    <ul class="flex flex-col py-4">
        <li>
        <a href="/" class="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-gray-500 hover:text-gray-800">
            <span class="inline-flex items-center justify-center h-12 w-12 text-lg text-gray-400"><i class="bx bx-home"></i></span>
            <span class="text-sm font-medium">Home</span>
        </a>
        </li>
        {% if request.user.is_authenticated %} 
        <li>
            <a href="{% url 'feed:follow_post' %}" class="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-gray-500 hover:text-gray-800">
                <span class="inline-flex items-center justify-center h-12 w-12 text-lg text-gray-400"><i class="bx bx-user-check"></i></span>
                <span class="text-sm font-medium">Following</span>
            </a>
        </li>
        <li>
            <a href="{% url 'profiles:detail' user.username %}" class="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-gray-500 hover:text-gray-800">
                <span class="inline-flex items-center justify-center h-12 w-12 text-lg text-gray-400"><i class="bx bxs-user bx-tada-hover"></i></span>
                <span class="text-sm font-medium">My Profile</span>
            </a>
        </li>
        <li>
            <a href="{% url 'notify:listar_notificacoes'%}" class="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-gray-500 hover:text-gray-800">
                <span class="inline-flex items-center justify-center h-12 w-12 text-lg text-gray-400"><i class='bx bxs-bell bx-tada-hover'></i></span>
                <span class="text-sm font-medium">Notifications</span>
            </a>
        </li>
        <li>
            <a href="{% url 'profile' %}" class="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-gray-500 hover:text-gray-800">
                <span class="inline-flex items-center justify-center h-12 w-12 text-lg text-gray-400"><i class="bx bx-edit"></i></span>
                <span class="text-sm font-medium">Edit Profile</span>
            </a>
        </li>     
        <li class="mt-full">
            <a href="{% url 'account_logout' %}" class="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-gray-500 hover:text-gray-800">
                <span class="inline-flex items-center justify-center h-12 w-12 text-lg text-gray-400"><i class="bx bx-log-out"></i></span>
                <span class="text-sm font-medium">Logout</span>
            </a>
        </li>
        {% else %}
            <li>
                <a href="{% url 'account_signup' %}" class="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-gray-500 hover:text-gray-800">
                <span class="inline-flex items-center justify-center h-12 w-12 text-lg text-gray-400"><i class="bx bx-user-plus"></i></span>
                <span class="text-sm font-medium">Register</span>
                </a>
            </li>
            <li>
                <a href="{% url 'account_login' %}" class="flex flex-row items-center h-12 transform hover:translate-x-2 transition-transform ease-in duration-200 text-gray-500 hover:text-gray-800">
                <span class="inline-flex items-center justify-center h-12 w-12 text-lg text-gray-400"><i class="bx bx-log-in"></i></span>
                <span class="text-sm font-medium">LogIn</span>
                </a>
            </li>
        {% endif %}
    </ul>
</div>

uni/3ºano/2ºsemestre/Opção/TPW-main/WHISP_TPW-PROJECT1/Whisp/templates/includes/post.html
{% load static %}

{% load thumbnail %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Whisp{% endblock %}</title>
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link rel="stylesheet" href="https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css" />
</head>

<body>
    <div class="flex justify-center">
    <div class="max-w-2xl max-h-xl px-10 my-4 py-6 bg-white rounded-lg shadow-md" style='width:50rem;'>
        <div class="flex justify-between items-center w-full">
            <span class="font-light text-gray-600">{{ post.date|date:"F j, Y, g:i:a" }}</span>
        </div>
        <div class="mt-2">
            <p class="mt-3 text-gray-800 font-semibold text-lg">{{ post.text }}</p>
            {% if post.image %}
                {% thumbnail post.image "300x300" crop="center" as im %}
                    <img src="{{ im.url }}" alt="Post Image" class="mt-3 max-w-full">
                {% endthumbnail %}
            {% endif %}
            
            {% if post.video %}
                <video controls class="mt-3 max-w-full auto-play-video">
                    <source src="{{ post.video.url }}" type="video/mp4">
                    Seu navegador não suporta a reprodução de vídeos.
                </video>
            {% endif %}
        </div>
        <div class="flex justify-between items-center mt-3">
            {% if show_detail_link %}
                <a class="text-blue-600 hover:underline" href="{% url 'feed:detail' post.id %}">Read More</a>

                <a href="{% url 'feed:detail' post.id %}">
                    <span class="text-gray-600 ml-2">{{ post.comments.count }} <i class='bx bx-comment' ></i></span>
                </a>
                {% if request.user.is_authenticated %} 
                <form action="{% url 'feed:likepost' %}" method="POST" class="ui form" data-post-id="{{ post.id }}" onclick="likePost(this)">
                    {% csrf_token %}
                    <input type="hidden" name="post_id" value="{{post.id}}">
                    {%if user not in post.likes.all %}
                        <button class="ui button positive" type="submit"><strong>{{post.likes.all.count}} <i class='bx bx-heart' ></i></strong></button>
                    {%else%}
                        <button class="text-red-500" type="submit"><strong>{{post.likes.all.count}}<i class='bx bxs-heart'></i></strong></button>
                    {% endif %}
                </form>
                {%else%}
                    <span class="text-gray-600 ml-2">{{ post.likes.all.count }} <i class='bx bx-heart' ></i></span>
                {% endif %}
               
            
                
            {% else %}
                {% if user.username == post.author.username or user.is_superuser %}
                    <div class="m-3 mx-0 mb-0">
                        <a href="{% url 'feed:delete' post.id %}" class="bg-white text-gray-800 font-bold rounded border-b-2 border-red-500 hover:border-red-600 hover:bg-red-500 hover:text-white shadow-md py-2 px-6 inline-flex items-center delete-toggle-modal">
                            <span class="mr-2">Delete Post</span>
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                                <path fill="currentcolor" d="M19 6.41L17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12 19 6.41z"/>
                            </svg>
                        </a>
                    </div>
                        <span class="text-gray-600 ml-2">{{ post.comments.count }} <i class='bx bx-comment' ></i></span>
                    <form action="{% url 'feed:likepost' %}" method="POST" class="ui form" data-post-id="{{ post.id }}" onclick="likePost(this)">
                        {% csrf_token %}
                        <input type="hidden" name="post_id" value="{{post.id}}">
                        {%if user not in post.likes.all %}
                            <button class="ui button positive" type="submit"><strong>{{post.likes.all.count}} <i class='bx bx-heart' ></i></strong></button>
                        {%else%}
                            <button class="text-red-500" type="submit"><strong>{{post.likes.all.count}}<i class='bx bxs-heart'></i></strong></button>
                        {% endif %}
                    </form>
                {% else %}
                    <span class="text-gray-600 ml-2">{{ post.comments.count }} <i class='bx bx-comment' ></i></span>
                    {% if request.user.is_authenticated %} 
                    <form action="{% url 'feed:likepost' %}" method="POST" class="ui form" data-post-id="{{ post.id }}" onclick="likePost(this)">
                        {% csrf_token %}
                        <input type="hidden" name="post_id" value="{{post.id}}">
                        {%if user not in post.likes.all %}
                            <button class="ui button positive" type="submit"><strong>{{post.likes.all.count}} <i class='bx bx-heart' ></i></strong></button>
                        {%else%}
                            <button class="text-red-500" type="submit"><strong>{{post.likes.all.count}}<i class='bx bxs-heart'></i></strong></button>
                        {% endif %}
                    </form>
                    {%else%}
                        <span class="text-gray-600 ml-2">{{ post.likes.all.count }} <i class='bx bx-heart' ></i></span>
                    {% endif %}
                {% endif %}
            {% endif %}
            
            <div>
                <a class="flex items-center" href="{% url 'profiles:detail' post.author.username %}">
                    {% thumbnail post.author.profile.image "373x373" crop="center" as im %}
                        <img src="{{ im.url }}" class='mx-4 w-10 h-10 object-cover rounded-full hidden sm:block' alt='avatar'>
                    {% endthumbnail %}
                    <h1 class="text-gray-700 font-bold">{{post.author.username}}</h1>
                </a>
            </div>
        </div>
    </div>
    </div>
    <script src="{% static 'js/main.js' %}"></script>
</body>